
------------------------------------------------------------
-- USERS
------------------------------------------------------------
CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255)  NOT NULL,
    role           VARCHAR(20)   NOT NULL,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_app_user_role CHECK (role IN ('USER', 'PREMIUM_USER', 'ADMIN'))
);

CREATE INDEX idx_app_user_role ON app_user(role);

------------------------------------------------------------
-- PRODUCTS
------------------------------------------------------------
CREATE TABLE product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)   NOT NULL,
    description  VARCHAR(2000)  NULL,
    price        NUMERIC(10,2)  NOT NULL,
    quantity     INT           NOT NULL,

    deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMP     NULL,

    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_product_name      ON product(name);
CREATE INDEX idx_product_price     ON product(price);
CREATE INDEX idx_product_quantity  ON product(quantity);
CREATE INDEX idx_product_deleted   ON product(deleted);

------------------------------------------------------------
-- ORDERS
------------------------------------------------------------
CREATE TABLE customer_order (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,

    subtotal       NUMERIC(10,2) NOT NULL,
    discount_total NUMERIC(10,2) NOT NULL DEFAULT 0,
    total          NUMERIC(10,2) NOT NULL,

    status         VARCHAR(20)   NOT NULL,

    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_order_user_created ON customer_order(user_id, created_at);
CREATE INDEX idx_order_status       ON customer_order(status);

------------------------------------------------------------
-- ORDER ITEMS
------------------------------------------------------------
CREATE TABLE order_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT        NOT NULL,
    product_id       BIGINT        NOT NULL,

    quantity         INT           NOT NULL,
    unit_price       NUMERIC(10,2) NOT NULL,

    discount_applied NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_price      NUMERIC(10,2) NOT NULL,

    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_item_order   FOREIGN KEY (order_id)   REFERENCES customer_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product(id)

);

CREATE INDEX idx_order_item_order   ON order_item(order_id);
CREATE INDEX idx_order_item_product ON order_item(product_id);